stages:
  - package

Package:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:27.3.1
  stage: package
  services:
    - docker:20.10.16-dind
  variables:
    CI_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - docker build -t $CI_IMAGE_TAG .
    - docker push $CI_IMAGE_TAG
